name: scp copy folder to remote via SSH

on:
  push:
    branches:
      - master
      - release/*
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup demo
        run: |
          mkdir dist
          touch dist/oof.txt
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: scp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
